# railway.toml
project = "api-maps-backend"

[services]

  # Serviço principal: web app Laravel
  [services.web]
  name = "api-maps-backend-web"
  start = "php artisan serve --host=0.0.0.0 --port=$PORT"
  # Porta do Railway que o container expõe
  port = 8080
  environment = "production"

  # Serviço Worker: Laravel Scheduler
  [services.scheduler]
  name = "api-maps-backend-scheduler"
  start = "sh run-scheduler.sh"
  # Esse serviço não precisa expor porta
  port = 0
  environment = "production"
